name: Code Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: PHPStan
            run: composer phpstan

          - name: Unit tests
            run: composer test

        php:
          - '8.0'
          - '8.1'
          - '8.2'

    name: ${{ matrix.actions.name }} at PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      # see https://github.com/actions/cache/blob/main/examples.md#php---composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            **/composer.lock
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install Composer
        run: composer update --no-progress

      - run: ${{ matrix.actions.run }}
