name: Code Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: PHPStan
            run: composer phpstan

    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        # see https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          coverage: none

      - name: Install Composer
        run: composer install --no-progress

      - run: ${{ matrix.actions.run }}
